source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.2'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'Parse', '~> 1.8.0'
pod 'ParseFacebookUtilsV4'
pod 'SDWebImage', '~>3.6'
pod 'UIActivityIndicator-for-SDWebImage'

use_frameworks!